import random

bookSeriesList = [
    "A Song of Ice and Fire",
    "Arkham Horror",
    "Book of Ice",
    "Conan the Barbarian",
    "Der 13. Paladin",
    "Der Clan Der Wölfe",
    "Der Drachenflüsterer",
    "Der Pfad des Magiers",
    "Diablo",
    "Die Alchemisten",
    "Die Chroniken von Mistle End",
    "Die Feuerreiter Seiner Majestät",
    "Die Greifenreiterin",
    "Die Scholomance",
    "Die Schule der Alyxa",
    "Eagles of the Empire",
    "Ender's Saga",
    "Endling",
    "First Law World",
    "Gaius Valerius Verrens",
    "Gentleman Bastards",
    "Grim Company",
    "Grishaverse",
    "Hall of Smoke",
    "Kingdom of the Wicked Series",
    "Klänge-Saga",
    "Knights Templar",
    "League of Legends Novels",
    "Lovecraftian Horror",
    "Mistborn",
    "Nachtstein",
    "Nekromanten",
    "Nimmerherz Legende",
    "Of Blood and Bone",
    "Praetorian",
    "Red Queen",
    "Shade of Devil",
    "Splitterwelt",
    "Star Wars",
    "Star Wars The High Republic",
    "Sturmfels Chroniken",
    "The Band",
    "The Bloodsworn Saga",
    "The Dark Tower",
    "The Dresden Files",
    "The Locked Tomb",
    "The Maleficent Seven",
    "The Memoirs of Lady Trent",
    "The Nevernight Chronicle",
    "The Poppy War",
    "The Realm of the Elderlings",
    "The Red Queen's War",
    "The Stormlight Archive",
    "The Sword of Kaigen",
    "The Vagrant",
    "The War Eternal",
    "The Wheel of Time",
    "Throne of Glass",
    "Under the Northern Sky",
    "Warcraft",
    "Warrior Cats",
    "Zane gegen die Götter"
]

bookSelected = random.randint(1, len(bookSeriesList))
print("Next book series to read is number {} - {} ".format(bookSelected+1, bookSeriesList[bookSelected]))
